app:
  security:
    jwt:
      privateKey: 123abcxyzconchotoanmditmemaytin
      prefix: Bearer
      authHeader: Authorization
      keyExpiresAt: 3600000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: 2251120374@ut.edu.vn

  kafka:
    bootstrap-servers: localhost:9092

endpoint:
  confirmUser: http://localhost:8080/api/v1/auth/confirm